// 图六类条目的机械读取真源在 `plugin-sdk`（graph-gate 是读侧语义 owner）。
// 本文件保留同名 re-export 面，供本包既有直接 import 解析；读取口径、链式回溯与访问子均单源。

export {
  MAX_CHAIN,
  attributionOf,
  chainEntries,
  contractCost,
  contractEffects,
  contractId,
  contractIndex,
  contractInputs,
  contractOutputs,
  contractPost,
  contractPre,
  contractPublishes,
  contractReads,
  edgePorts,
  edgeWhen,
  effectsCaps,
  effectsMethods,
  effectsPorts,
  graphDerivedFrom,
  graphEdges,
  graphEntrySupply,
  graphLoop,
  graphNodes,
  graphSink,
  isLlmContract,
  nodeAutonomy,
  nodeBindings,
  nodeContractId,
  nodeEntry,
  nodeId,
  nodeImpl,
  nodeLinks,
  nodeScope,
  nodeSubgraph,
  numericThreshold,
  readEntries,
  readGraphModel,
  readPrompts,
  readThresholds,
  retriableOf,
  touchesEffects,
} from 'plugin-sdk'
export type { GraphModel } from 'plugin-sdk'
